"""Create DeliveryBoy table

Revision ID: aea47b1d7ff3
Revises: a138b3111166
Create Date: 2026-02-16 14:49:55.008563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea47b1d7ff3'
down_revision = 'a138b3111166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_delivery_boy_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'delivery_boys', ['delivery_boy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_delivery_boy_id_fkey'), 'users', ['delivery_boy_id'], ['id'])

    # ### end Alembic commands ###
